# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements from pyproject.toml and uv.lock if needed
# Install pip dependencies

# Install system build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy the project files
COPY . /app

# Install pip dependencies using pip (ignore scripts if needed)
RUN pip install --upgrade pip && pip install .

# Expose port if needed

# Command to run the MCP server
CMD ["python", "main.py"]
